# Generated by Django 5.0.8 on 2024-09-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultylogin',
            old_name='Name',
            new_name='FullName',
        ),
    ]
