# Generated by Django 5.0.8 on 2024-09-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_exam_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('img', models.ImageField(upload_to='media/')),
                ('ques', models.CharField(max_length=600)),
                ('opt1', models.CharField(max_length=200)),
                ('opt2', models.CharField(max_length=200)),
                ('opt3', models.CharField(default=None, max_length=200)),
                ('opt4', models.CharField(default=None, max_length=200)),
                ('ans', models.CharField(max_length=201)),
                ('sub', models.CharField(max_length=11)),
                ('ques_setter', models.CharField(max_length=51)),
            ],
        ),
    ]
