# Generated by Django 5.0.8 on 2024-09-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
