# Generated by Django 5.0.8 on 2024-09-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_rename_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(default=None, upload_to='q_img/'),
        ),
    ]
