# Generated by Django 5.0.8 on 2024-10-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0006_alter_question_img'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_ans', models.CharField(default=None, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.question')),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.studinfo')),
            ],
        ),
    ]
