# Generated by Django 5.0.8 on 2024-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0008_rename_question_examsubmission_ques_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmission',
            name='ques_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='rollno',
            field=models.CharField(max_length=10),
        ),
    ]
