# Generated by Django 5.0.8 on 2024-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0009_alter_examsubmission_ques_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='exam_sub',
            field=models.CharField(default='No', max_length=11),
        ),
    ]
