# Generated by Django 5.0.8 on 2024-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0011_remove_examsubmission_exam_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='exam_sub',
            field=models.CharField(default='Math', max_length=11),
        ),
    ]
