# Generated by Django 5.0.8 on 2024-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0012_examsubmission_exam_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmission',
            name='exam_sub',
            field=models.CharField(max_length=11),
        ),
    ]
