# Generated by Django 5.0.8 on 2024-10-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0013_alter_examsubmission_exam_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='full_name',
            field=models.CharField(default='ffff', max_length=50),
            preserve_default=False,
        ),
    ]
