# Generated by Django 5.0.8 on 2024-09-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('institute', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('verifyStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
